CFLAGS = -std=gnu11 -Wall -Werror -Wextra -O2

.PHONY: all clean

all: task1_client task1_server task2

clean:
	$(RM) task1_client task1_server task2

task1_client: task1_client.c
task1_server: task1_server.c
task2: task2.c